name: Full test suite

on:
  release:
    types: [created]
  schedule:
  - cron:  '0 0 1 * *'
  workflow_dispatch:
    
env:
  COMPILE_JOBS: ${{ vars.NCPUS || 1 }}
  CXX_FLAGS: "-Werror -Wall -Wextra -Wno-ignored-optimization-argument"
  MPI_NPROC: ${{ vars.NCPUS || 1 }}

jobs:
  full-test-suite:
    name: Full test suite ${{ matrix.build_type }}-dealii:${{ matrix.dealii_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Release", "Debug"]
        dealii_version: ["v9.6.0", "master"]
    
    container:
      image: dealii/dealii:${{ matrix.dealii_version }}-noble
      options: --user root

    steps:
      - name: Install node-v18 # Needed for checkout
        run: |
          sudo apt-get install -y nodejs

      - uses: actions/checkout@v4

      # - name: Install clang-tidy
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y --no-install-recommends clang-tidy

      - name: Configure cmake
        run: |
          cmake -S . -B build -DEXAMPLES=ON -DTESTS=ON \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_CXX_FLAGS="${{ env.CXX_FLAGS }}"

      - name: Compile
        run: |
          make --directory=build -j${{ env.COMPILE_JOBS }}
       
      - name: Test
        env:
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
          TEST_LABEL: full-suite-${{ matrix.build_type }}
        run: |
          cd build
          echo "Running tests with label ${{ env.TEST_LABEL }}"
          ctest --output-on-failure -L ${{ env.TEST_LABEL }}
