name: Full test suite

on:
  release:
    types: [created]
  schedule:
  - cron:  '0 0 1 * *'
  workflow_dispatch:
    
env:
  COMPILE_JOBS: 2
  CXX_FLAGS: "-Werror -Wall -Wextra"
  MPI_NPROC: 2

jobs:
  full-test-suite:
    name: Full test suite ${{ matrix.build_type }}-dealii:${{ matrix.dealii_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Release", "Debug"]
        dealii_version: ["v9.6.0", "master"]
    
    container:
      image: dealii/dealii:${{ matrix.dealii_version }}-focal
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Compile
        run: |
          cmake -S . -B build -DSAPPHIRE=On -DVFP=ON -DEXAMPLES=ON -DTESTS=ON \
                -DCMAKE_CXX_FLAGS="${{ env.CXX_FLAGS }}" \
                -DCMAKE_CXX_CLANG_TIDY="clang-tidy;--extra-arg=-Wno-error=unknown-warning-option" \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          make --directory=build -j${{ env.COMPILE_JOBS }}
       
      - name: Test
        env:
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
          TEST_LABEL: full-suite-${{ matrix.build_type }}
        run: |
          cd build
          echo "Running tests with label ${{ env.TEST_LABEL }}"
          ctest -V -L ${{ env.TEST_LABEL }}
