name: GitHub CI

on:
  push:
    branches:
        - main
        - devel
  pull_request:
    branches:
        - main
        - devel
#   schedule:
#   - cron:  '0 0 * * *'
    
env:
  COMPILE_JOBS: 2
  CXX_FLAGS: "-Werror -Wall -Wextra"

jobs:
  build:
    name: Build ${{ matrix.build_type }}-dealii:${{ matrix.dealii_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Release", "Debug"]
        dealii_version: ["v9.5.0"]
    
    container:
      image: dealii/dealii:${{ matrix.dealii_version }}-focal
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Compile
        run: |
          cmake -S . -B build -DSAPPHIRE=On -DVFP=ON -DEXAMPLES=ON -DTESTS=ON \
                -DCMAKE_CXX_FLAGS="${{ env.CXX_FLAGS }}" \
                -DCMAKE_CXX_CLANG_TIDY="clang-tidy;--extra-arg=-Wno-error=unknown-warning-option" \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cd build
          make -j${{ env.COMPILE_JOBS }}
       
      - name: Test (main branch)
        if: github.ref == 'refs/heads/main'
        env:
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
        run: |
          cd build
          ctest -V

      - name: Test (devel branch)
        if: github.ref == 'refs/heads/devel'
        env:
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
        run: |
          cd build
          ctest -V -L commmit