name: GitHub CI

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
  workflow_dispatch:
    
env:
  COMPILE_JOBS: ${{ vars.NCPUS || 1 }}
  CXX_FLAGS: "-Werror -Wall -Wextra -Wno-ignored-optimization-argument"
  MPI_NPROC: ${{ vars.NCPUS || 1 }}

jobs:
  tests:
    name: Build and test ${{ matrix.build_type }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        build_type: ["Release", "Debug"]
    
    container:
      image: sapphirepp/sapphirepp:latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile
        # Removed clang-tidy flag:
        # -DCMAKE_CXX_CLANG_TIDY="clang-tidy;--extra-arg=-Wno-error=unknown-warning-option" \
        run: |
          cmake -S . -B build -DSAPPHIREPP=ON -DVFP=ON -DEXAMPLES=ON -DTESTS=ON \
                -DCMAKE_CXX_FLAGS="${{ env.CXX_FLAGS }}" \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          make --directory=build -j${{ env.COMPILE_JOBS }}
       
      - name: Test
        env:
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
          TEST_LABEL: commit-${{ matrix.build_type }}
        run: |
          cd build
          echo "Running tests with label ${{ env.TEST_LABEL }}"
          ctest -V -L ${{ env.TEST_LABEL }}
