name: GitHub CI

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
  workflow_dispatch:
    
env:
  COMPILE_JOBS: ${{ vars.NCPUS || 1 }}
  CXX_FLAGS: "-Werror -Wall -Wextra -Wno-ignored-optimization-argument"
  MPI_NPROC: ${{ vars.NCPUS || 1 }}

jobs:
  tests:
    name: Build and test ${{ matrix.build_type }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        build_type: ["Release", "Debug"]
    
    container:
      image: sapphirepp/sapphirepp:latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure cmake
        run: |
          cmake -S . -B build -DEXAMPLES=ON -DTESTS=ON -DDOC=ON \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_CXX_FLAGS="${{ env.CXX_FLAGS }}" \
                -DCMAKE_CXX_CLANG_TIDY="clang-tidy-19;--extra-arg=-Wno-error=unknown-warning-option" \
                -DCLANG_FORMAT_EXECUTABLE="clang-format-19"

      - name: Check clang-format style
        run: |
          make --directory=build clang-format-check

      - name: Check Documentation
        run: |
          echo "Build target doc"
          make --directory=build doc >&-

      - name: Compile
        run: |
          make --directory=build -j${{ env.COMPILE_JOBS }}

      - name: Test
        env:
          TEST_LABEL: commit-${{ matrix.build_type }}
        run: |
          cd build
          echo "Running tests with label ${{ env.TEST_LABEL }}"
          ctest --output-on-failure -L ${{ env.TEST_LABEL }}
